name: Release to npm

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release to npm
    uses: ./.github/workflows/publish-npm.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    with:
      mode: release
